### ISSUE TITLE
Oficial recordings of the invasion of the Brazilian capital at 8th of January of 2023

### ISSUE THREAD

**Issue by guiga-zalu** [RCcola1987/Archival-Preservation#1]
It's an OneDrive file system (it'd be a Nextcloud one, if it wasn't for Bill Gates).

The link is te following: https://drive.presidencia.gov.br/public/615ba7

There are 33 folders ranging from 2 to 8 GB of `.dav` files on each one.

**Comment by RCcola1987** [comment]
Ok so this was an epic PITA. The SharePoint site fails to download any archive bigger than 19GB and in turn it meant that each folder had to be downloaded in parts. This wouldn't be so bad except that SharePoint is limited to 9MBps so it takes forever.

I have fully archived the site to Archive.org. The total size was Aprox 700GB.

If you value my efforts please share my site to people you know. https://ryancarter.info
